### ISSUE TITLE
Investigate possible issues related to grounding, power consumption

### ISSUE THREAD

**Issue by kurtmh** [bakkerthehacker/serqet#35]
I was talking with someone doing a project similar to ours, in that it involved making a PCB with a battery and a Bluetooth module, and he mentioned that there were some issues they came across related to grounding everything properly/safely and unforeseen huge power consumption with the Bluetooth module. This may not end up being a huge deal if we chose parts to prevent these things from happening, but it's worth paying attention to for considering if we'd need to make some PCB or battery changes early on.

**Comment by aadavids** [comment]
LOL YUP
