### ISSUE TITLE
Find a good PCB manufacturer

### ISSUE THREAD

**Issue by kurtmh** [bakkerthehacker/serqet#36]
Links I've gathered:
http://www.4pcb.com/
http://www.seeedstudio.com/service/index.php?r=pcb
https://oshpark.com/ 
Word on the street is "Pretty sure all 3 will apply solder mask, no stencils tho( if you're designing anything that's leadless) and will do e-tests for free. "

http://volterainc.com/ Word on the street is " if you know tron/mech people, they're beta testing their printer for 10 bux/board" "Apparently Voltera doesn't have a drill/pick and place attachment, so no holes/vias or assembly help if you're using that" "talk to alroy from voltera in waterloo"
http://imall.iteadstudio.com/open-pcb/pcb-prototyping.html

Carl says sticking with 2 layers makes everything much cheaper.

**Comment by kurtmh** [comment]
Our current approximate guide for pricing is <$200 for 20 boards.

**Comment by kurtmh** [comment]
http://www.apcircuits.com/ recommended in course notes.

**Comment by kurtmh** [comment]
On Campus: https://uwaterloo.ca/3d-print-centre/circuit-board-manufacturing. I went today and asked about rough pricing and got a figure of ~$16/board depending on complexity. It's the same price per board for additional boards. They don't do verification but they said they haven't heard of issues in a while.

**Comment by kurtmh** [comment]
Oshpark.com can be used for a quick quote. Carl says they take about 2 weeks. There is crimp circuits in Toronto which could take much less time but will cost more. There's also still the school. Carl says there's 3 more places in Waterloo.

**Comment by aadavids** [comment]
done
