### ISSUE TITLE
Decide on PCB layout tool 

### ISSUE THREAD

**Issue by kurtmh** [bakkerthehacker/serqet#51]
Our options seem to be Upverter, free eagle, full version of eagle, and kicad. Sticking with 2 layers apparently makes it all much cheaper. Carl verified that the 2 free layers includes ALL layers you'd want on the PCB including power and ground.

**Comment by bakkerthehacker** [comment]
Eagle https://bakker.pw/torrent_files/Cadsoft%20Eagle%20Professional%206.6.0/Cadsoft%20Eagle%20Professional%206.6.0.rar
